barclays_payments:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: KM09008
      user: GMCGINLAY
      authenticator: snowflake
      database: BARCLAYS_DEMO
      warehouse: BARCLAYS_DEMO_WH
      schema: ANALYTICS
      role: SYSADMIN
      threads: 4
