-- =====================================================
-- BARCLAYS ZERO TO SNOWFLAKE
-- STEP 4: CORTEX AI ENRICHMENT
-- Duration: ~20 minutes
-- Pre-req: dbt models deployed (Step 3c) OR run after views created
-- =====================================================

USE WAREHOUSE BARCLAYS_DEMO_WH;
USE SCHEMA BARCLAYS_DEMO.ANALYTICS;


-- 4.1: Sentiment Analysis on customer feedback
CREATE OR REPLACE TABLE FEEDBACK_ENRICHED AS
SELECT
    f.FEEDBACK_ID,
    f.FEEDBACK_DATE,
    f.CUSTOMER_NAME,
    f.FEEDBACK_CHANNEL,
    f.FEEDBACK_TEXT,
    f.PAYMENT_TYPE,
    f.RATING,
    ROUND(SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT), 3) AS SENTIMENT_SCORE,
    CASE
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT) >  0.3 THEN 'POSITIVE'
        WHEN SNOWFLAKE.CORTEX.SENTIMENT(f.FEEDBACK_TEXT) < -0.3 THEN 'NEGATIVE'
        ELSE 'NEUTRAL'
    END AS SENTIMENT_LABEL,
    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        f.FEEDBACK_TEXT,
        ['Performance Issue','Service Quality','Technical Problem','Positive Experience','Feature Request']
    ):label::STRING AS TOPIC_CATEGORY,
    SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
        f.FEEDBACK_TEXT,
        ['Performance Issue','Service Quality','Technical Problem','Positive Experience','Feature Request']
    ):score::FLOAT AS CLASSIFICATION_CONFIDENCE
FROM BARCLAYS_DEMO.RAW.CUSTOMER_FEEDBACK f;

-- Preview enriched feedback
SELECT
    LEFT(FEEDBACK_TEXT, 80) || '...' AS PREVIEW,
    SENTIMENT_SCORE,
    SENTIMENT_LABEL,
    TOPIC_CATEGORY,
    ROUND(CLASSIFICATION_CONFIDENCE, 2) AS CONFIDENCE
FROM FEEDBACK_ENRICHED
ORDER BY SENTIMENT_SCORE
LIMIT 10;


-- 4.2: AI-generated recommended actions for high-severity alerts
SELECT
    a.ALERT_ID,
    a.SEVERITY,
    a.ALERT_DESCRIPTION,
    a.PAYMENT_TYPE,
    SNOWFLAKE.CORTEX.COMPLETE(
        'mistral-large2',
        'You are a payments operations analyst at a major UK bank. ' ||
        'Given this alert: "' || a.ALERT_DESCRIPTION || '" ' ||
        'for payment type: ' || a.PAYMENT_TYPE || ' ' ||
        'with severity: ' || a.SEVERITY || '. ' ||
        'Provide a one-sentence recommended action.'
    ) AS AI_RECOMMENDED_ACTION
FROM BARCLAYS_DEMO.RAW.OPERATIONAL_ALERTS a
WHERE a.STATUS = 'OPEN' AND a.SEVERITY IN ('HIGH','CRITICAL')
LIMIT 5;


-- 4.3: Sentiment distribution
SELECT
    SENTIMENT_LABEL,
    COUNT(*) AS FEEDBACK_COUNT,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SCORE,
    ROUND(COUNT(*)::FLOAT / (SELECT COUNT(*) FROM FEEDBACK_ENRICHED) * 100, 1) AS PERCENTAGE
FROM FEEDBACK_ENRICHED
GROUP BY SENTIMENT_LABEL
ORDER BY FEEDBACK_COUNT DESC;


-- 4.4: Sentiment by payment type
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS TOTAL_FEEDBACK,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END) AS NEGATIVE_COUNT,
    ROUND(COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END)::FLOAT / COUNT(*) * 100, 1) AS NEGATIVE_PCT
FROM FEEDBACK_ENRICHED
GROUP BY PAYMENT_TYPE
ORDER BY AVG_SENTIMENT ASC;


-- =====================================================
-- 4.5: AI-POWERED DYNAMIC TABLES
-- These refresh automatically when source data changes
-- =====================================================

-- DT 1: Live Negative Sentiment Feed
CREATE OR REPLACE DYNAMIC TABLE PREPARED.DT_NEGATIVE_SENTIMENT_FEED
    TARGET_LAG = '1 minute'
    WAREHOUSE = BARCLAYS_DEMO_WH
AS
SELECT
    FEEDBACK_ID, FEEDBACK_DATE, CUSTOMER_NAME,
    PAYMENT_TYPE, FEEDBACK_CHANNEL, FEEDBACK_TEXT,
    SENTIMENT_SCORE, TOPIC_CATEGORY, CLASSIFICATION_CONFIDENCE
FROM FEEDBACK_ENRICHED
WHERE SENTIMENT_LABEL = 'NEGATIVE'
ORDER BY FEEDBACK_DATE DESC;

SELECT * FROM PREPARED.DT_NEGATIVE_SENTIMENT_FEED LIMIT 10;

-- DT 2: Operational Sentiment Summary
CREATE OR REPLACE DYNAMIC TABLE PREPARED.DT_SENTIMENT_OPS_SUMMARY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = BARCLAYS_DEMO_WH
AS
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS TOTAL_FEEDBACK,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END) AS NEGATIVE_COUNT,
    COUNT(CASE WHEN SENTIMENT_LABEL = 'POSITIVE' THEN 1 END) AS POSITIVE_COUNT,
    ROUND(AVG(SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
    ROUND(COUNT(CASE WHEN SENTIMENT_LABEL = 'NEGATIVE' THEN 1 END)::FLOAT / COUNT(*) * 100, 1) AS NEGATIVE_PCT,
    MAX(FEEDBACK_DATE) AS LATEST_FEEDBACK
FROM FEEDBACK_ENRICHED
GROUP BY PAYMENT_TYPE;

SELECT * FROM PREPARED.DT_SENTIMENT_OPS_SUMMARY ORDER BY NEGATIVE_PCT DESC;

-- DT 3: Live SLA Breach Counter (requires dbt mart)
CREATE OR REPLACE DYNAMIC TABLE PREPARED.DT_LIVE_BREACH_COUNT
    TARGET_LAG = '1 minute'
    WAREHOUSE = BARCLAYS_DEMO_WH
AS
SELECT
    PAYMENT_TYPE,
    COUNT(*) AS BREACH_DAYS,
    MIN(PAYMENT_DATE) AS FIRST_BREACH,
    MAX(PAYMENT_DATE) AS LATEST_BREACH
FROM ANALYTICS.MART_SLA_COMPLIANCE
WHERE SLA_STATUS = 'BREACH'
  AND PAYMENT_DATE >= DATEADD('day', -7, CURRENT_DATE())
GROUP BY PAYMENT_TYPE;

SELECT * FROM PREPARED.DT_LIVE_BREACH_COUNT ORDER BY BREACH_DAYS DESC;

-- Monitor Dynamic Table health
SHOW DYNAMIC TABLES IN DATABASE BARCLAYS_DEMO;
